name: Doxygen build

on: [push]


jobs:
  build_windows:
    name: Doxygen build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v1
     - name: Configure CI Git User
       run: |
         git remote rm origin
         git remote add origin "https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/deadbeef-for-windows/deadbeef.git"
         git fetch
         git config --global user.email octobot@github.com
         git config --global user.name GitHub Actions
       env:
         GITHUB_PAT: ${{ secrets.PAT_GH }}
     - name: Get Doxygen
       run: sudo apt-get --yes --force-yes install doxygen
     - name: Get prev docs
       run: mkdir -p docs/html && git --work-tree=docs/html checkout origin/gh-pages -- . && git --work-tree=docs/html checkout gh-pages
     - name: Compile documentation
       run: DATE="`date \"+%Y-%m-%d\"`" && doxygen
     - name: Commit changes
       run: git config --global user.email octobot@github.com && git config --global user.name GitHub Actions && git --work-tree=docs/html add -A && DATE="`date \"+%Y-%m-%d\"`" git commit -m "Commit generated by GitHub Actions on $DATE."
     - name: Push updated docs
       run: git --work-tree=docs/html push --set-upstream origin gh-pages


