name: Build for macOS

on: [ push, pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: build
      run: TRAVIS_OS_NAME=osx travis/build.sh
    - name: Upload
      env:
          gh_rsa_key: ${{ secrets.GH_ENCRYPTED_RSA_KEY }}
          gh_rsa_iv: ${{ secrets.GH_ENCRYPTED_RSA_IV }}
      run: TRAVIS_OS_NAME=osx travis/upload.sh
