name: Build for Windows

on: [push]

jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Get sha_short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain mingw-w64-x86_64-libzip mingw-w64-x86_64-pkg-config mingw-w64-x86_64-dlfcn
          git make tar unzip xz zip mingw-w64-x86_64-clang mingw-w64-x86_64-libblocksruntime
          mingw-w64-x86_64-jansson mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtk2 mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-flac mingw-w64-x86_64-curl mingw-w64-x86_64-portaudio mingw-w64-x86_64-faad2 mingw-w64-x86_64-flac
          mingw-w64-x86_64-wavpack mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libogg mingw-w64-x86_64-opusfile mingw-w64-x86_64-opus
          mingw-w64-x86_64-libsndfile mingw-w64-x86_64-libsamplerate mingw-w64-x86_64-yasm
    - name: Run ./travis/build.sh
      shell: msys2 {0}
      run: |
        export TRAVIS_OS_NAME=windows
        source ./travis/build.sh
    - name: Upload artifact windows-debug-${{ steps.vars.outputs.sha_short }}.zip
      uses: actions/upload-artifact@v1
      with:
        name: windows-debug-${{ steps.vars.outputs.sha_short }}
        path: ./bin/debug/
